name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --pull --no-cache mysqlrouter/ -f mysqlrouter/Dockerfile --tag localbuild/mysqlrouter:latest
    - uses: anchore/scan-action@v2
      with:
        image: "localbuild/mysqlrouter:latest"
        fail-build: false
    - name: grype scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
